# These are supported funding model platforms
patreon: sousadev
custom: https://play.google.com/store/apps/details?id=com.SousaDev.Tap2Fly&hl=pt
youtube: https://www.youtube.com/watch?v=XJf_O1HYdFU&t
